#ifndef CLASSUTIL_H
#define CLASSUTIL_H

#define CONSTRUCT_STRUCT(CLASSNAME, CONSTRUCT_NAME) CONSTRUCT_STRUCT_ADDITIONAL_SPACE(CLASSNAME, CONSTRUCT_NAME, 0)

#define CONSTRUCT_STRUCT_ADDITIONAL_SPACE(CLASSNAME, CONSTRUCT_NAME, SPACE) \
    CLASSNAME *CONSTRUCT_NAME;  \
    CONSTRUCT_NAME = malloc(sizeof(*CONSTRUCT_NAME) + SPACE);   \
    if (CONSTRUCT_NAME == NULL) {   \
        return NULL;    \
    }   \
    memset(CONSTRUCT_NAME, 0, sizeof(*CONSTRUCT_NAME) + SPACE);

#define DESTROY_METHOD(CLASSNAME) inline void destroy##CLASSNAME(CLASSNAME *self) {free(self);}

#endif